### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dpalacio** [mishapsi/godot_gizmo#1]
Can't use this project without licensing information

**Comment by suprafun** [comment]
Just want to bump this.

**Comment by Frontrider** [comment]
I can use it on 3.3.4, but I guess it is rewrite time.

**Comment by bkeys** [comment]
I was actually just about to bring up the same issue.

**Comment by mishapsi** [comment]
Sorry I just remembered to add a license now, I'm not use to making publically available repos
